site_name: APIs Transporte Público Galicia
site_url: https://tpgalicia.github.io
docs_dir: docs

repo_url: https://github.com/tpgalicia/tpgalicia.github.io
repo_name: GitHub
edit_uri: blob/main/docs/

copyright: Copyright © 2024-2025 Grupo TPGalicia. Todos los derechos reservados.

theme:
  language: es
  name: material
  
  palette:
    primary: teal
    accent: teal

  features:
    - content.action.edit
    - content.action.view
    - navigation.footer

  font: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Inicio: index.md
  - Transporte autonómico: 
    - Introducción: autonomic/index.md
    - Operadores:
      - ALSA: autonomic/operator/alsa.md
      - Arriva: autonomic/operator/arriva.md
      - Monbus: autonomic/operator/monbus.md
  - Transporte urbano:
    - A Coruña: urban/coruna/
    - Ferrol: urban/ferrol.md
    - Lugo: urban/lugo.md
    - Ourense: urban/ourense.md
    - Pontevedra: urban/pontevedra.md
    - Santiago de Compostela: urban/santiago.md
    - Vigo: urban/vigo.md
  - Servicios ferroviarios:
    - Renfe: train/renfe.md
    - FEVE: train/feve.md
  - Otros:
    - NAP: other/nap.md
    - Bicicleta pública: other/bike.md

  
